### ISSUE TITLE
Did you complete the full implementation of paper Deep Compression?

### ISSUE THREAD

**Issue by kingofoz** [hiteshvaidya/Model-Compression#1]
Hi @hiteshvaidya 
I'd like to have a try if so.

Thanks.

**Comment by hiteshvaidya** [comment]
Hi @kingofoz ,
Sorry for replying so late. The original code is in caffe and it is really painful to execute it in caffe. And I don't even have a gpu on top of it. I tried using tensorflow but the problem is, tensorflow has fixed set of functions. So as per my knowledge, I couldn't find functions to reduce weight values. That is why, I couldn't complete it.
